Ecommerce Analysis Project

In [69]:
import numpy as np 
import pandas as pd

In [70]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\Mohd Shamsher\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\Mohd Shamsher\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [71]:
df = pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 551 entries, 0 to 550
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       551 non-null    str
 1   Order_Date     551 non-null    str
 2   Customer_Name  551 non-null    str
 3   Email          551 non-null    str
 4   Phone          529 non-null    float64
 5   City           551 non-null    str
 6   State          551 non-null    str
 7   Product        551 non-null    str
 8   Category       551 non-null    str
 9   Qty            480 non-null    float64
 10  Unit_Price     493 non-null    float64
 11  Discount       478 non-null    object
 12  Payment_Mode   551 non-null    str
 13  Order_Status   551 non-null    str
 14  Delivery_Date  530 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 64.7+ KB

In [73]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [74]:
# statstics
df.describe()

              Phone         Qty   Unit_Price
count  5.290000e+02  480.000000   493.000000
mean   9.548173e+09    2.793750  3138.756592
std    2.613213e+08    1.946348  2958.507359
min    9.104441e+09   -1.000000   499.000000
25%    9.324548e+09    1.000000   999.000000
50%    9.541696e+09    3.000000  1999.000000
75%    9.792041e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [75]:
# data set shape
df.shape

(551, 15)

In [76]:
# step 4 check missing 
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              71
Unit_Price       58
Discount         73
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [77]:
# step 5 check duplicate records
df.duplicated().sum()

np.int64(11)

In [78]:
# Remoce duplicate records
df.drop_duplicates(inplace=True)

In [79]:
df.duplicated().sum()

np.int64(0)

In [80]:
# Replace invalid values
# Replace comman invalid values with NaN
df.replace(['N/A', 'NULL',''],np.nan,inplace=True)
df.sample(7)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
526,ORD16015,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
548,ORD16037,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
469,ORD1471,15-06-2025,Sneha,sneha54@gmail.com,9.944717e+09,Delhi,Delhi,Laptop,Electronics,4.0,2599.0,20,COD,Returned,21-06-2025
181,ORD1183,12-04-2025,Amit,amit77@gmail.com,9.241602e+09,Delhi,Delhi,Bottle,Home,4.0,9999.0,20,NetBanking,Cancelled,18-04-2025
386,ORD1388,14-05-2025,Rahul,rahul15@gmail.com,9.666480e+09,Mumbai,Maharashtra,Shoes,Fashion,NaN,1499.0,15,Card,Returned,18-05-2025
314,ORD1316,14-02-2025,Amit,amit95@gmail.com,9.399341e+09,Jaipur,Rajasthan,Bottle,Home,3.0,NaN,15,UPI,Delivered,22-02-2025

In [81]:
# step 7 remove extra spaces
df  = df.apply(lambda x : x.str.strip() if x.dtype == 'object' else x)

In [82]:
# step 8 Standardize text format
# convert text into proper format
df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.title()

In [83]:
# step 9 valid email address
# keep only valid email address
df = df[df['Email'].str.contains('@',na=False)]

In [84]:
# step 10 Convert Date Format
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce') # NAT
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'], errors='coerce')

C:\Users\Mohd Shamsher\AppData\Local\Temp\ipykernel_6928\604734311.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce') # NAT

In [85]:
# 11 convert numeric columns 
cols = ['Qty','Unit_Price','Discount']
for c in cols:
    df[c] = pd.to_numeric(df[c], errors='coerce')

In [86]:
# step 12 Remove invalid quantity
# reomve records having negative or zero quantity
df = df[df['Qty']>0]

In [87]:
# step 13 fill missing values
df['Discount'] = df['Discount'].fillna(0)
df['Phone'] = df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [88]:
# step 14 Feature Engineering
df['Sales'] = df['Qty']* df['Unit_Price']
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-09-02,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-08-05,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0

In [89]:
# Net Amount 
df['Net_Amount']= (df['Sales'] - df['Discount']/10)
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-09-02,24995.0,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-08-05,5997.0,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0

In [90]:
# Profit (Example 20%)
df['Profit'] = df['Net_Amount']*0.02
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.0,159.92
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-09-02,24995.0,24995.0,499.90
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-08-05,5997.0,5997.0,119.94
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0,29.94
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,799.92

In [91]:
# order month
df['month']  = df['Order_Date'].dt.month_name()

In [92]:
# order year
df['Year'] = df['Order_Date'].dt.year
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,month,Year
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.0,159.92,June,2025.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-09-02,24995.0,24995.0,499.90,February,2025.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-08-05,5997.0,5997.0,119.94,May,2025.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0,29.94,February,2025.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,799.92,February,2025.0

In [93]:
df['Weekday'] = df['Order_Date'].dt.day_name()
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-03-07,7996.0,7996.0,159.92,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,0.0,Card,Pending,2025-09-02,24995.0,24995.0,499.90,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,0.0,COD,Returned,2025-08-05,5997.0,5997.0,119.94,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0,29.94,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.0,799.92,February,2025.0,Monday

In [94]:
# step 15 final visualization
df.info()

<class 'pandas.DataFrame'>
Index: 401 entries, 0 to 550
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       401 non-null    str
 1   Order_Date     352 non-null    datetime64[us]
 2   Customer_Name  401 non-null    str
 3   Email          401 non-null    str
 4   Phone          401 non-null    object
 5   City           401 non-null    str
 6   State          401 non-null    str
 7   Product        401 non-null    str
 8   Category       401 non-null    str
 9   Qty            401 non-null    float64
 10  Unit_Price     361 non-null    float64
 11  Discount       401 non-null    float64
 12  Payment_Mode   401 non-null    str
 13  Order_Status   401 non-null    str
 14  Delivery_Date  367 non-null    datetime64[us]
 15  Sales          361 non-null    float64
 16  Net_Amount     361 non-null    float64
 17  Profit         361 non-null    float64
 18  month          352 non-null    str
 19  Year           352 non-null    float64
 20  Weekday        352 non-null    str
dtypes: datetime64[us](2), float64(7), object(1), str(11)
memory usage: 68.9+ KB

In [95]:
df.isnull().sum()

Order_ID          0
Order_Date       49
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       40
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date    34
Sales            40
Net_Amount       40
Profit           40
month            49
Year             49
Weekday          49
dtype: int64

In [96]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,352,401.000000,361.000000,401.0,367,361.000000,361.000000,361.000000,352.0
mean,2025-04-01 15:28:38.181818,3.311721,3223.099723,0.0,2025-05-01 04:22:53.297002,11062.318560,11062.318560,221.246371,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.0,2025-01-02 00:00:00,499.000000,499.000000,9.980000,2025.0
25%,2025-02-13 00:00:00,2.000000,999.000000,0.0,2025-02-16 12:00:00,2997.000000,2997.000000,59.940000,2025.0
50%,2025-04-04 00:00:00,3.000000,1999.000000,0.0,2025-04-17 00:00:00,5997.000000,5997.000000,119.940000,2025.0
75%,2025-05-15 00:00:00,5.000000,4999.000000,0.0,2025-06-18 00:00:00,12995.000000,12995.000000,259.900000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,0.0,2025-12-06 00:00:00,49995.000000,49995.000000,999.900000,2025.0
std,NaN,1.443983,3021.524786,0.0,NaN,12212.726261,12212.726261,244.254525,0.0

In [97]:
# step 16 Export clean data
df.to_csv('Clean_Ecommerce_data.csv', index=False)

In [98]:
%pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in c:\Users\Mohd Shamsher\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\Users\Mohd Shamsher\AppData\Local\Programs\Python\Python313\Lib\site-packages (from SQLAlchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Mohd Shamsher\AppData\Roaming\Python\Python313\site-packages (from SQLAlchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [99]:
%pip install PyMySQL

Requirement already satisfied: PyMySQL in c:\Users\Mohd Shamsher\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

done installation

In [100]:
# step 17 import data into mysql
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:root@localhost/ecommerce')

In [101]:
# export dataframe to mysql
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SHOW TABLES"))
    print(result.fetchall())

[('orders',)]

In [102]:
df.shape

(401, 21)